### ISSUE TITLE
sphere_virtual_machine.kubevm1: 1 error(s) occurred: vsphere_virtual_machine.kubevm3: unexpected EOF while creating VMs

### ISSUE THREAD

**Issue by scundall** [kubernetes/kubernetes-anywhere#448]
5 error(s) occurred:

* vsphere_virtual_machine.kubevm3: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: unexpected EOF
* vsphere_virtual_machine.kubevm2: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: unexpected EOF
* vsphere_virtual_machine.kubevm5: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: unexpected EOF
* vsphere_virtual_machine.kubevm1: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: unexpected EOF
* vsphere_virtual_machine.kubevm4: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: runtime error: invalid memory address or nil pointer dereference
2017/09/13 07:49:39 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3ddadbf]
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 
2017/09/13 07:49:39 [DEBUG] plugin: terraform: goroutine 89 [running]:
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object.DistributedVirtualPortgroup.EthernetCardBackingInfo(0xc4203b9400, 0xc4209cd6c0, 0x1b, 0xc4207d8790, 0x10, 0xc420483460, 0x1e, 0x7f0ab066a000, 0xc4200563b8, 0x490fe80, ...)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object/distributed_virtual_portgroup.go:52 +0x24f
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/vendor/github.com/vmware/govmomi/object.(*DistributedVirtualPortgroup).EthernetCardBackingInfo(0xc420855500, 0x7f0ab066a000, 0xc4200563b8, 0x7f0ab066a000, 0xc4200563b8, 0x79e0ec0, 0xc420855500)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	<autogenerated>:446 +0x87
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.buildNetworkDevice(0xc4208a5bc0, 0xc4207d87a4, 0x7, 0x5064801, 0x7, 0x0, 0x0, 0x0, 0x1b, 0x79d03c0)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1472 +0x157
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.(*virtualMachine).setupVirtualMachine(0xc420010300, 0xc42088ec90, 0x5, 0x42ff360)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:1833 +0xde9
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/vsphere.resourceVSphereVirtualMachineCreate(0xc420314380, 0x4f70780, 0xc42088ec90, 0x0, 0x0)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/vsphere/resource_vsphere_virtual_machine.go:900 +0x17f7
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203c7920, 0xc420280be0, 0xc4207c0de0, 0x4f70780, 0xc42088ec90, 0x1, 0x28, 0xc4208a8a50)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc42031eaf0, 0xc420280b90, 0xc420280be0, 0xc4207c0de0, 0x7f0ab0866000, 0x0, 0x0)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2017/09/13 07:49:39 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420870fe0, 0xc4207c0d40, 0xc4207d8980, 0x0, 0x0)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2017/09/13 07:49:39 [DEBUG] plugin: terraform: reflect.Value.call(0xc4203c0120, 0xc420797e98, 0x13, 0x505c04a, 0x4, 0xc4206d4f20, 0x3, 0x3, 0x0, 0x0, ...)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/09/13 07:49:39 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4203c0120, 0xc420797e98, 0x13, 0xc4205d7720, 0x3, 0x3, 0x0, 0x0, 0x0)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/09/13 07:49:39 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420839d80, 0xc420839d40, 0xc420845080, 0xc420573300, 0xc420726440, 0x41f8a80, 0xc4207c0d40, 0x16, 0x41f8ac0, 0xc4207d8980, ...)
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/09/13 07:49:39 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/09/13 07:49:39 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalIf
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: unexpected EOF
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm3: unexpected EOF
2017/09/13 07:49:39 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm3
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalIf
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: unexpected EOF
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm2: unexpected EOF
2017/09/13 07:49:39 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm2
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalIf
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalIf
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: unexpected EOF
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm1: unexpected EOF
2017/09/13 07:49:39 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm1
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "tls_cert_request.kubernetes-master"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "tls_locally_signed_cert.kubernetes-master"
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: unexpected EOF
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm5: unexpected EOF
2017/09/13 07:49:39 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm5
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provider.tls (close)"
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalIf
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteState
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalWriteDiff
2017/09/13 07:49:39 [DEBUG] root: eval: *terraform.EvalApplyPost
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: unexpected EOF
2017/09/13 07:49:39 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* vsphere_virtual_machine.kubevm4: unexpected EOF
2017/09/13 07:49:39 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm4
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_master"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-master"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provisioner.local-exec (close)"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provider.vsphere (close)"
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_node"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node2"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node5"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node3"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provider.template (close)"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node4"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provider.null (close)"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2017/09/13 07:49:39 [DEBUG] dag/walk: upstream errored, not walking "root"
2017/09/13 07:49:39 [TRACE] Preserving existing state lineage "c23257d2-4bb4-462b-bfcb-e3e0c7b2cb7f"
2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [WARN] plugin: error closing client during Kill: connection is shut down
2017/09/13 07:49:39 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/09/13 07:49:39 [ERR] plugin: plugin server: accept unix /tmp/plugin751621487: use of closed network connection
2017/09/13 07:49:39 [DEBUG] plugin: terraform: template-provider (internal) 2017/09/13 07:49:39 [ERR] plugin: plugin server: accept unix /tmp/plugin453119946: use of closed network connection
2017/09/13 07:49:39 [DEBUG] plugin: terraform: template-provider (internal) 2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [DEBUG] plugin: terraform: tls-provider (internal) 2017/09/13 07:49:39 [ERR] plugin: plugin server: accept unix /tmp/plugin169909967: use of closed network connection
2017/09/13 07:49:39 [DEBUG] plugin: terraform: null-provider (internal) 2017/09/13 07:49:39 [ERR] plugin: plugin server: accept unix /tmp/plugin179249613: use of closed network connection
2017/09/13 07:49:39 [DEBUG] plugin: terraform: null-provider (internal) 2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [DEBUG] plugin: terraform: tls-provider (internal) 2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited
2017/09/13 07:49:39 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2017/09/13 07:49:39 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/09/13 07:49:39 [DEBUG] plugin: /bin/terraform: plugin process exited

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1

**Comment by scundall** [comment]
vsphere 6.5

**Comment by scundall** [comment]
Maybe the interesting tip about this situation could be that we ended up getting same error while installing it using 2 users on 2 different operation systems Windows & MacOS (Sierra)
