### ISSUE TITLE
Terraform crashes

### ISSUE THREAD

**Issue by martinmike2** [kubernetes/kubernetes-anywhere#570]
Using the recommended kubernetes version on vSphere 6 I get a terraform crash on tls_cert_request.kubernetes-master create

Makefile:70: recipe for target 'do' failed

**Comment by martinmike2** [comment]
Some more information:

Error applying plan:

1 error(s) occurred:

* tls_cert_request.kubernetes-master: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface {} is nil, not string
2018/10/03 03:50:11 [DEBUG] plugin: terraform:
2018/10/03 03:50:11 [DEBUG] plugin: terraform: goroutine 108 [running]:
2018/10/03 03:50:11 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/tls.CreateCertRequest(0xc420348620, 0x0, 0x0, 0x0, 0x0)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/tls/resource_cert_request.go:101 +0x80d
2018/10/03 03:50:11 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc4203418c0, 0xc42037efa0, 0xc4205c3880, 0x0, 0x0, 0x1, 0x28, 0xc42039eae0)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:186 +0x48d
2018/10/03 03:50:11 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc420169b20, 0xc42037ef50, 0xc42037efa0, 0xc4205c3880, 0x7f55104c3000, 0x0, 0x0)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:242 +0x9b
2018/10/03 03:50:11 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc420510320, 0xc4205c3820, 0xc420496ef0, 0x0, 0x0)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x57
2018/10/03 03:50:11 [DEBUG] plugin: terraform: reflect.Value.call(0xc4204442a0, 0xc4201de330, 0x13, 0x505c04a, 0x4, 0xc42065cf20, 0x3, 0x3, 0x0, 0x0, ...)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2018/10/03 03:50:11 [DEBUG] plugin: terraform: reflect.Value.Call(0xc4204442a0, 0xc4201de330, 0x13, 0xc420087720, 0x3, 0x3, 0x0, 0x0, 0x0)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2018/10/03 03:50:11 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc420197e00, 0xc420197d80, 0xc4201dcb18, 0xc420546180, 0xc4204e6620, 0x41f8a80, 0xc4205c3820, 0x16, 0x41f8ac0, 0xc420496ef0, ...)
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2018/10/03 03:50:11 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2018/10/03 03:50:11 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2018/10/03 03:50:11 [DEBUG] plugin: terraform: vsphere-provider (internal) 2018/10/03 03:50:11 [DEBUG] "datastore1"
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteState
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalIf
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteState
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteDiff
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalApplyPost
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalUpdateStateHook
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited
2018/10/03 03:50:11 [TRACE] Preserving existing state lineage "6e046140-bb3c-43f7-98f5-eca5592fc184"
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteState
2018/10/03 03:50:11 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.kubevm5
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalApplyProvisioners
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalIf
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteState
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalWriteDiff
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalApplyPost
2018/10/03 03:50:11 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF
2018/10/03 03:50:11 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* tls_cert_request.kubernetes-master: unexpected EOF
2018/10/03 03:50:11 [DEBUG] dag/walk: walking "provider.vsphere (close)"
2018/10/03 03:50:11 [DEBUG] vertex 'root.provider.vsphere (close)': walking
2018/10/03 03:50:11 [DEBUG] vertex 'root.provider.vsphere (close)': evaluating
2018/10/03 03:50:11 [TRACE] [walkApply] Entering eval tree: provider.vsphere (close)
2018/10/03 03:50:11 [DEBUG] root: eval: *terraform.EvalCloseProvider
2018/10/03 03:50:11 [TRACE] [walkApply] Exiting eval tree: provider.vsphere (close)
2018/10/03 03:50:11 [TRACE] [walkApply] Exiting eval tree: tls_cert_request.kubernetes-master
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "tls_locally_signed_cert.kubernetes-master"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_master"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "data.template_file.configure_node"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "provider.tls (close)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node4"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node3"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-master"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node5"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "provisioner.local-exec (close)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "provider.template (close)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "null_resource.kubernetes-node2"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "meta.count-boundary (count boundary fixup)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "provider.null (close)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "provisioner.remote-exec (close)"
2018/10/03 03:50:11 [DEBUG] dag/walk: upstream errored, not walking "root"
2018/10/03 03:50:11 [TRACE] Preserving existing state lineage "6e046140-bb3c-43f7-98f5-eca5592fc184"
2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [WARN] plugin: error closing client during Kill: connection is shut down
2018/10/03 03:50:11 [DEBUG] plugin: terraform: null-provider (internal) 2018/10/03 03:50:11 [ERR] plugin: plugin server: accept unix /tmp/plugin411518522: use of closed network connection
2018/10/03 03:50:11 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2018/10/03 03:50:11 [ERR] plugin: plugin server: accept unix /tmp/plugin525940921: use of closed network connection
2018/10/03 03:50:11 [DEBUG] plugin: terraform: remote-exec-provisioner (internal) 2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2018/10/03 03:50:11 [ERR] plugin: plugin server: accept unix /tmp/plugin092098747: use of closed network connection
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited
2018/10/03 03:50:11 [DEBUG] plugin: terraform: null-provider (internal) 2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [DEBUG] plugin: terraform: template-provider (internal) 2018/10/03 03:50:11 [ERR] plugin: plugin server: accept unix /tmp/plugin230126902: use of closed network connection
2018/10/03 03:50:11 [DEBUG] plugin: terraform: template-provider (internal) 2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited
2018/10/03 03:50:11 [DEBUG] plugin: terraform: local-exec-provisioner (internal) 2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited
2018/10/03 03:50:11 [DEBUG] plugin: terraform: vsphere-provider (internal) 2018/10/03 03:50:11 [ERR] plugin: plugin server: accept unix /tmp/plugin857605938: use of closed network connection
2018/10/03 03:50:11 [DEBUG] plugin: terraform: vsphere-provider (internal) 2018/10/03 03:50:11 [DEBUG] plugin: waiting for all plugin processes to complete...
2018/10/03 03:50:11 [DEBUG] plugin: /bin/terraform: plugin process exited



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
Makefile:70: recipe for target 'do' failed
make[1]: *** [do] Error 1
make[1]: Leaving directory '/opt/kubernetes-anywhere'
Makefile:48: recipe for target 'deploy-cluster' failed
make: *** [deploy-cluster] Error 2
